id: I01F44748
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T09:48:13+00:00'
last_modified: '2022-06-08T06:39:37.367576+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W5062
  title: གསུང་འབུམ། མི་ཕམ་རྒྱ་མཚོ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    '5657':
      image_group_id: I1KG8540
      title: ''
      total_pages: 707
      order: 1
      base_file: 5657.txt
    555D:
      image_group_id: I1KG8541
      title: ''
      total_pages: 775
      order: 2
      base_file: 555D.txt
    3CF2:
      image_group_id: I1KG8542
      title: ''
      total_pages: 880
      order: 3
      base_file: 3CF2.txt
    E97D:
      image_group_id: I1KG8543
      title: ''
      total_pages: 693
      order: 4
      base_file: E97D.txt
    1B76:
      image_group_id: I1KG8544
      title: ''
      total_pages: 897
      order: 5
      base_file: 1B76.txt
    B0AF:
      image_group_id: I1KG8545
      title: ''
      total_pages: 786
      order: 6
      base_file: B0AF.txt
    DD99:
      image_group_id: I1KG8546
      title: ''
      total_pages: 744
      order: 7
      base_file: DD99.txt
    '5879':
      image_group_id: I1KG8547
      title: ''
      total_pages: 686
      order: 8
      base_file: 5879.txt
    29A9:
      image_group_id: I1KG8548
      title: ''
      total_pages: 856
      order: 9
      base_file: 29A9.txt
    '8707':
      image_group_id: I1KG8549
      title: ''
      total_pages: 854
      order: 10
      base_file: 8707.txt
    7BEF:
      image_group_id: I1KG8550
      title: ''
      total_pages: 835
      order: 11
      base_file: 7BEF.txt
    '5131':
      image_group_id: I1KG8551
      title: ''
      total_pages: 743
      order: 12
      base_file: 5131.txt
    '4588':
      image_group_id: I1KG8552
      title: ''
      total_pages: 701
      order: 13
      base_file: 4588.txt
    1DA0:
      image_group_id: I1KG8553
      title: ''
      total_pages: 1023
      order: 14
      base_file: 1DA0.txt
    D7A2:
      image_group_id: I1KG8554
      title: ''
      total_pages: 862
      order: 15
      base_file: D7A2.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
